<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="data_glove">

  <xacro:macro name="floating_joint" params="child parent">
    <link name="${child}"/>
    <joint name="${child}_joint" type="floating">
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
  </xacro:macro>

  <link name="world"/>
<!--
  <xacro:floating_joint child="lf_knuckle_imu" parent="world"/>
  <xacro:floating_joint child="lf_middle_imu" parent="world"/>
  <xacro:floating_joint child="lf_distal_imu" parent="world"/>
  <xacro:floating_joint child="rf_knuckle_imu" parent="world"/>
  <xacro:floating_joint child="rf_middle_imu" parent="world"/>
  <xacro:floating_joint child="rf_distal_imu" parent="world"/>
  <xacro:floating_joint child="mf_knuckle_imu" parent="world"/>
  <xacro:floating_joint child="mf_middle_imu" parent="world"/>
  <xacro:floating_joint child="mf_distal_imu" parent="world"/>
  <xacro:floating_joint child="ff_knuckle_imu" parent="world"/>
  <xacro:floating_joint child="ff_middle_imu" parent="world"/>
  <xacro:floating_joint child="ff_distal_imu" parent="world"/>
  <xacro:floating_joint child="th_knuckle_imu" parent="world"/>
  <xacro:floating_joint child="th_middle_imu" parent="world"/>
  <xacro:floating_joint child="th_distal_imu" parent="world"/>
  <xacro:floating_joint child="palm_imu" parent="world"/>
  <xacro:floating_joint child="arm_imu" parent="world"/>
  <xacro:floating_joint child="wrist_imu" parent="world"/>
-->

  <xacro:macro name="finger" params="prefix parent origin l_knuckle l_middle l_distal">
    <link name="${prefix}_knuckle">
      <visual>
        <origin xyz="${l_knuckle/2} 0.0 0.0" rpy="0 -1.57 0"/>
        <geometry>
          <cylinder length="${l_knuckle}" radius="0.01"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <link name="${prefix}_middle">
      <visual>
        <origin xyz="${l_middle/2} 0.0 0.0" rpy="0 -1.57 0"/>
        <geometry>
          <cylinder length="${l_middle}" radius="0.01"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <link name="${prefix}_distal">
      <visual>
        <origin xyz="${l_distal/2} 0.0 0.0" rpy="0 -1.57 0"/>
        <geometry>
          <cylinder length="${l_distal}" radius="0.01"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_j3" type="revolute">
      <parent link="${parent}"/>
      <child link="${prefix}_knuckle" />
      <origin xyz="${origin}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit upper="1.57079" lower="0" effort="1000.0" velocity="0.5"/>
    </joint>
  
    <joint name="${prefix}_j2" type="revolute">
      <parent link="${prefix}_knuckle"/>
      <child link="${prefix}_middle" />
      <origin xyz="${l_knuckle} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit upper="1.57079" lower="0" effort="1000.0" velocity="0.5"/>
    </joint>
  
    <joint name="${prefix}_j1" type="revolute">
      <parent link="${prefix}_middle"/>
      <child link="${prefix}_distal" />
      <origin xyz="${l_middle} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit upper="1.57079" lower="0" effort="1000.0" velocity="0.5"/>
    </joint>
 
  </xacro:macro>

  
  <link name="wrist"/>
<!--
  <joint name="world_wrist" type="floating">
    <parent link="world"/>
    <child link="wrist" />
  </joint>
-->
  <joint name="world_wrist" type="fixed">
    <parent link="world"/>
    <child link="wrist" />
    <origin xyz="0.0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="palm">
    <visual>
      <geometry>
        <box size="0.11 0.1 0.025"/>
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>

  <xacro:finger prefix="ff" parent="palm" origin="0.055 0.04 0" l_knuckle="0.06" l_middle="0.04" l_distal="0.03"/>
  <xacro:finger prefix="mf" parent="palm" origin="0.055 0.015 0" l_knuckle="0.065" l_middle="0.045" l_distal="0.03"/>
  <xacro:finger prefix="rf" parent="palm" origin="0.055 -0.01 0" l_knuckle="0.06" l_middle="0.04" l_distal="0.03"/>
  <xacro:finger prefix="lf" parent="palm" origin="0.055 -0.035 0" l_knuckle="0.05" l_middle="0.03" l_distal="0.03"/>

  <joint name="wrist_palm" type="fixed">
    <parent link="wrist"/>
    <child link="palm"/>
    <origin xyz="0.055 0 0" rpy="0 0 0"/>
  </joint>
</robot>
